version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    # ports:
    #   - 3333:3333
    # volumes:
    #   - ./backend:/home/node/api
    networks:
      - proxy-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:rw
      - ./certbot/letsencrypt/:/etc/letsencrypt/:ro
      - ./certbot/www/:/var/www/certbot/:ro
    networks:
      - proxy-net

networks:
  proxy-net:
    driver: bridge